name: Github Release 2 (aldur)

on:
  push:
    branches:
      - "docker_release_poc_override"

concurrency:
  group: docker-image-source-${{ github.head_ref || github.ref || github.run_id }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

jobs:
  ## Runs anytime `ci.yml` runs or when manually called
  image:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      ## Build a maximum of 2 images concurrently based on matrix.dist
      max-parallel: 2
      matrix:
        dist:
          - debian
    steps:
      ## Setup Docker for the builds
      - name: Docker setup
        id: docker_setup
        uses: stacks-network/actions/docker@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      ## Set docker metatdata
      - name: Docker Metadata ( ${{matrix.dist}} )
        id: docker_metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
        with:
          images: |
            ${{env.docker-org}}/${{ github.event.repository.name }}
            ${{env.docker-org}}/stacks-blockchain
          tags: |
            type=raw,value=release-aldur-docker_releases_poc
            type=ref,event=pr

      ## Build docker image
      - name: Build and Push ( ${{matrix.dist}} )
        id: docker_build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          file: ./.github/actions/dockerfiles/Dockerfile.${{matrix.dist}}-source
          platforms: ${{ env.docker_platforms }}
          tags: blockstack/stacks-blockchain:release-aldur-docker_releases_poc
          labels: ${{ steps.docker_metadata.outputs.labels }}
          build-args: |
            STACKS_NODE_VERSION=${{ env.GITHUB_SHA_SHORT }}
            GIT_BRANCH=${{ env.GITHUB_REF_SHORT }}
            GIT_COMMIT=${{ env.GITHUB_SHA_SHORT }}
            TARGET_CPU=x86-64-v3
          push: ${{ env.DOCKER_PUSH }}
