name: Github Release (aldur)

on:
  push:
    branches:
      - "docker_releases_poc"

concurrency:
  group: github-release-${{ github.head_ref || github.ref }}
  ## Always cancel duplicate jobs
  cancel-in-progress: true

run-name: "docker_releases_poc"

jobs:
  docker-image:
    name: Docker Image (Binary)
    uses: ./.github/workflows/image-build-source.yml
    with:
      tag: "aldur-docker_releases_poc"
      docker_tag: "release-aldur-docker_releases_poc"
    secrets: inherit
