## Run Stacks Signer Unit Tests
name: Tests::Stacks Signer Unit Tests

on:
  workflow_call:

env:
  RUST_BACKTRACE: full
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3
  TEST_TIMEOUT: 30

concurrency:
  group: stacks-core-tests-${{ github.head_ref || github.ref || github.run_id }}
  # Only cancel in progress if this is for a PR
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the latest code
      - name: Checkout Latest Code
        uses: actions/checkout@v3

      # Install Rust toolchain
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Run unit tests
      - name: Run Unit Tests
        run: cargo test -p stacks-signer -- --nocapture --test-threads 1
        continue-on-error: true

      # Upload code coverage results
      - name: Code Coverage
        uses: stacks-network/actions/codecov@main
        with:
          test-name: stacks-signer-tests
